const Json = [
  [
    {
      image: "../img/Пицца/chiken-vasabi.png",
      quantity: "В наличии 3 шт",
      name: "Чикен-Васаби",
      price: "99 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Europe.png",
      quantity: "В наличии 7 шт",
      name: "Европейская",
      price: "101 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/peperoni.png",
      quantity: "В наличии 7 шт",
      name: "Пепперони",
      price: "95 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Italian.png",
      quantity: "В наличии 5 шт",
      name: "Итальянская",
      price: "79 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Palermo.png",
      quantity: "В наличии 4 шт",
      name: "Палермо",
      price: "86 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Margaritta.png",
      quantity: "В наличии 6 шт",
      name: "Маргарита",
      price: "96 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Italian.png",
      quantity: "В наличии 5 шт",
      name: "Итальянская",
      price: "79 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/chiken-vasabi.png",
      quantity: "В наличии 3 шт",
      name: "Чикен-Васаби",
      price: "99 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Europe.png",
      quantity: "В наличии 5 шт",
      name: "Европейская",
      price: "76 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Peperoni.png",
      quantity: "В наличии 7 шт",
      name: "Пепперони",
      price: "101 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Margaritta.png",
      quantity: "В наличии 6 шт",
      name: "Маргарита",
      price: "96 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Palermo.png",
      quantity: "В наличии 4 шт",
      name: "Палермо",
      price: "86 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/chiken-vasabi.png",
      quantity: "В наличии 3 шт",
      name: "Чикен-Васаби",
      price: "99 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Palermo.png",
      quantity: "В наличии 4 шт",
      name: "Палермо",
      price: "86 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Peperoni.png",
      quantity: "В наличии 7 шт",
      name: "Пепперони",
      price: "101 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Italian.png",
      quantity: "В наличии 5 шт",
      name: "Итальянская",
      price: "79 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Margaritta.png",
      quantity: "В наличии 6 шт",
      name: "Маргарита",
      price: "96 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Europe.png",
      quantity: "В наличии 5 шт",
      name: "Европейская",
      price: "76 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/chiken-vasabi.png",
      quantity: "В наличии 3 шт",
      name: "Чикен-Васаби",
      price: "99 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Europe.png",
      quantity: "В наличии 5 шт",
      name: "Европейская",
      price: "76 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Palermo.png",
      quantity: "В наличии 4 шт",
      name: "Палермо",
      price: "86 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Margaritta.png",
      quantity: "В наличии 6 шт",
      name: "Маргарита",
      price: "96 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Italian.png",
      quantity: "В наличии 5 шт",
      name: "Итальянская",
      price: "79 руб",
      basket: "В корзину",
    },
    {
      image: "../img/Пицца/Peperoni.png",
      quantity: "В наличии 7 шт",
      name: "Пепперони",
      price: "101 руб",
      basket: "В корзину",
    },
  ],
];

export default Json;
